<?php

namespace App\AdminBundle\Repository;

/**
 * ActualiteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ActualiteRepository extends \Doctrine\ORM\EntityRepository
{
	public function getActuDesc() {
	        $em = $this->getEntityManager();
                $qb = $em->getRepository('AppAdminBundle:Actualite')->createQueryBuilder('a');
                $qb->orderBy('a.id', 'DESC');

                return $qb->getQuery()->getResult();
	}

	public function getActuLimit() {
		$em = $this->getEntityManager();
                $qb = $em->getRepository('AppAdminBundle:Actualite')->createQueryBuilder('a');
                $qb->orderBy('a.id', 'DESC');
                $qb->setMaxResults(1);

                return $qb->getQuery()->getResult();
	}
}
