<?php

namespace App\AdminBundle\Repository;

/**
 * RealisationsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RealisationsRepository extends \Doctrine\ORM\EntityRepository
{

	public function getRealDesc() {
            $em = $this->getEntityManager();
            $qb = $em->getRepository('AppAdminBundle:Realisations')->createQueryBuilder('r');
            $qb->orderBy('r.id', 'DESC');

            return $qb->getQuery()->getResult();
	}

	public function getRealLimit() {
	    $em = $this->getEntityManager();
            $qb = $em->getRepository('AppAdminBundle:Realisations')->createQueryBuilder('r');
            $qb->orderBy('r.id', 'DESC');
            $qb->setMaxResults(3);

            return $qb->getQuery()->getResult();
	}
}
