<?php

namespace App\AdminBundle\Repository;

/**
 * SupportRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SupportRepository extends \Doctrine\ORM\EntityRepository
{ 
	public function getSupportTheme($theme) {
		$em = $this->getEntityManager();
		$qb = $em->getRepository('AppAdminBundle:Support')->createQueryBuilder('s');
		$qb->where('s.theme = :theme')->setParameter('theme', $theme);

		return $qb->getQuery()->getResult();
	}
}
